spring.application.name=desafio
spring.datasource.url=jdbc:postgresql://${DB_POSTGRESQL_HOST}/${DB_POSTGRESQL_NAME}
spring.datasource.username=${DB_POSTGRESQL_USERNAME}
spring.datasource.password=${DB_POSTGRESQL_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect
